Repository GoogleCloudPlatform/oozie-to-airflow, pull requests merged in 2019-05, with the labels that each got.

#186 Fix codecov reports
  .gitignore
  oozie-to-airflow/run-all-unit-tests
Labels: enhancement

#202 Updates file names for templates and fixed pre-commit to not add licence
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
Labels: dev-environment

#203 Refactor OozieParser tests
  oozie-to-airflow/tests/converter/test_oozie_parser.py
Labels: refactor

#207 Better description of caching for run-sys-tests
  CONTRIBUTING.md
Labels: documentation

#217 Use Jinja filter to clean variable name
  o2a/converter/parser.py
  o2a/templates/dag_body.tpl
  o2a/templates/decision.tpl
  o2a/templates/dummy.tpl
  o2a/templates/fs_op.tpl
  o2a/templates/git.tpl
  o2a/templates/kill.tpl
  o2a/templates/mapreduce.tpl
  o2a/templates/pig.tpl
  o2a/templates/prepare.tpl
  o2a/templates/shell.tpl
  o2a/templates/spark.tpl
  o2a/templates/ssh.tpl
  o2a/templates/subwf.tpl
  o2a/utils/template_utils.py
  o2a/utils/variable_name_utils.py
  tests/converter/test_oozie_parser.py
  tests/test_templates.py
  tests/utils/test_variable_name_utils.py
Labels: enhancement
