Repository GoogleCloudPlatform/oozie-to-airflow, pull requests merged in 2019-07, with the labels that each got.

#306 Unify retriving text from node
  o2a/mappers/pig_mapper.py
  o2a/mappers/shell_mapper.py
  o2a/mappers/spark_mapper.py
  o2a/mappers/ssh_mapper.py
  o2a/mappers/subworkflow_mapper.py
  o2a/utils/xml_utils.py
Labels: refactor

#319 Fix to pre-commit docs
  CONTRIBUTING.md
Labels: dev-environment

#280 Add Workflow Job Status Notification
  examples/advancedflow/job.properties
  examples/fs/job.properties
  examples/git/job.properties
  o2a/converter/oozie_converter.py
  o2a/converter/workflow.py
  o2a/o2a.py
  o2a/templates/http.tpl
  o2a/templates/http_command.tpl
  o2a/transformers/add_workflow_notificaton_transformer.py
  o2a/transformers/base_transformer.py
  o2a/transformers/remove_end_transformer.py
  o2a/transformers/remove_fork_transformer.py
  o2a/transformers/remove_inaccessible_node_transformer.py
  o2a/transformers/remove_join_transformer.py
  o2a/transformers/remove_kill_transformer.py
  o2a/transformers/remove_start_transformer.py
  tests/converter/test_oozie_converter.py
  tests/transformers/test_add_workflow_notification_transformer.py
  tests/transformers/test_inaccessible_node_transformer.py
  tests/transformers/test_remove_end_transformer.py
  tests/transformers/test_remove_fork_transformer.py
  tests/transformers/test_remove_join_transformer.py
  tests/transformers/test_remove_kill_transformer.py
  tests/transformers/test_remove_start_transformer.py
Labels: enhancement

#333 Bump mypy from 0.711 to 0.720
  .pre-commit-config.yaml
  .travis.yml
  mypy.ini
  requirements.txt
Labels: dependencies

#346 Maximum level of TOC set to 2
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
Labels: documentation

#347 Updated diagram
  images/o2a-dependecy-cycles.png
  images/o2a-dependencies.png
Labels: documentation

#373 Add wf:functions to known limitations
  README.md
Labels: documentation

#388 Added latest dependency graph
  images/o2a-dependencies.png
  images/o2a-dependency-cycles.png
Labels: documentation

#391 Improve information about EL-functions in README
  README.md
Labels: documentation
