Repository GoogleCloudPlatform/oozie-to-airflow, pull requests merged in 2019-04, with the labels that each got.

#41 Fix Sub-workflow's use of input arguments in the factory function
  oozie-to-airflow/mappers/subwf_mapper.py
  oozie-to-airflow/templates/dag.tpl
  oozie-to-airflow/templates/dag_subwf.tpl
  oozie-to-airflow/templates/subwf.tpl
Labels: bug

#43 Finalize the decision control node mapper
  oozie-to-airflow/examples/decision/.gitignore
  oozie-to-airflow/examples/decision/configuration-template.properties
  oozie-to-airflow/examples/decision/job.properties
  oozie-to-airflow/examples/decision/workflow.xml
  oozie-to-airflow/integration/run_decision_test_with_airflow.bash
  oozie-to-airflow/mappers/decision_mapper.py
  oozie-to-airflow/templates/decision.tpl
  oozie-to-airflow/tests/mappers/test_decision_mapper.py
Labels: enhancement

#40 Add Shell action mapper
  oozie-to-airflow/converter/oozie_parser.py
  oozie-to-airflow/examples/shell/configuration-template.properties
  oozie-to-airflow/examples/shell/configuration.properties
  oozie-to-airflow/examples/shell/job.properties
  oozie-to-airflow/examples/shell/workflow.xml
  oozie-to-airflow/integration/run_shell_test_with_airflow.bash
  oozie-to-airflow/mappers/shell_mapper.py
  oozie-to-airflow/templates/shell.tpl
  oozie-to-airflow/tests/mappers/test_shell_mapper.py
Labels: enhancement

#67 Add event system for mappers
  oozie-to-airflow/converter/oozie_converter.py
  oozie-to-airflow/converter/parser.py
  oozie-to-airflow/converter/primitives.py
  oozie-to-airflow/converter/relation.py
  oozie-to-airflow/converter/subworkflow_converter.py
  oozie-to-airflow/mappers/base_mapper.py
  oozie-to-airflow/mappers/file_archive_mixins.py
  oozie-to-airflow/mappers/pig_mapper.py
  oozie-to-airflow/tests/converter/test_oozie_converter.py
  oozie-to-airflow/tests/converter/test_oozie_parser.py
Labels: enhancement

#77 Fix init.sh: missing import and wrong requirements.txt location
  oozie-to-airflow/init.sh
Labels: bug

#74 Fix file and archive functionality
  oozie-to-airflow/converter/parser.py
  oozie-to-airflow/examples/pig/workflow.xml
  oozie-to-airflow/mappers/__init__.py
  oozie-to-airflow/mappers/file_archive_mappers.py
  oozie-to-airflow/mappers/pig_mapper.py
  oozie-to-airflow/tests/converter/test_oozie_parser.py
  oozie-to-airflow/tests/mappers/test_archive_mixin.py
  oozie-to-airflow/tests/mappers/test_file_mixin.py
  oozie-to-airflow/tests/mappers/test_pig_mapper.py
Labels: bug

#101 Add tests for subwf example
  .travis.yml
  oozie-to-airflow/mappers/subworkflow_mapper.py
  oozie-to-airflow/tests/converter/test_oozie_parser.py
Labels: enhancement

#100 Add composer Web UI URL preview and auto bucket discovery
  oozie-to-airflow/run-sys-test
Labels: enhancement

#61 Add FS mapper
  oozie-to-airflow/converter/exceptions.py
  oozie-to-airflow/converter/mappers.py
  oozie-to-airflow/converter/primitives.py
  oozie-to-airflow/examples/fs/configuration.template.properties
  oozie-to-airflow/examples/fs/job.properties
  oozie-to-airflow/examples/fs/workflow.xml
  oozie-to-airflow/examples/pig/workflow.xml
  oozie-to-airflow/mappers/fs_mapper.py
  oozie-to-airflow/mappers/prepare_mixin.py
  oozie-to-airflow/templates/fs.tpl
  oozie-to-airflow/templates/fs_op.tpl
  oozie-to-airflow/tests/converter/test_oozie_parser.py
  oozie-to-airflow/tests/mappers/test_fs_mapper.py
  oozie-to-airflow/tests/mappers/test_mapreduce_mapper.py
  oozie-to-airflow/tests/mappers/test_prepare_mixin.py
  oozie-to-airflow/tests/mappers/test_shell_mapper.py
  oozie-to-airflow/tests/utils/test_el_utils.py
  oozie-to-airflow/tests/utils/test_relation_utils.py
  oozie-to-airflow/utils/el_utils.py
  oozie-to-airflow/utils/relation_utils.py
  pylintrc
Labels: enhancement

#113 Add detection of missing configuration.properties to o2a.py
  oozie-to-airflow/converter/oozie_converter.py
  oozie-to-airflow/o2a.py
  oozie-to-airflow/utils/constants.py
  oozie-to-airflow/utils/el_utils.py
Labels: enhancement

#112 Update README to reflect recent changes and additions
  oozie-to-airflow/README.md
Labels: documentation

#126 Updated init action to include removal of jackson libraries
  README.md
  dataproc/oozie-5.1.sh
  oozie-to-airflow/README.md
  oozie-to-airflow/examples/shell/workflow.xml
  oozie-to-airflow/run-sys-test
Labels: bug

#128 Add XML schema validation in o2a.py before each conversion
  oozie-to-airflow/o2a.py
  oozie-to-airflow/utils/constants.py
  oozie-to-airflow/validate-all-workflows
  oozie-to-airflow/validate-workflows
Labels: enhancement
